#include <brass/codegen/ml_fusion.hpp>
#include <sstream>

namespace brass::codegen {

namespace {

std::string ptx_header(const target::PtxOptions& opts) {
    uint32_t major = opts.ptx_version_major;
    uint32_t minor = opts.ptx_version_minor;
    if (opts.sm_arch == "sm_89" && (major < 7 || (major == 7 && minor < 8))) {
        major = 7;
        minor = 8;
    }
    std::ostringstream ss;
    ss << "// Generated by Brass PTX Target Emitter\n"
       << ".version " << major << "." << minor << "\n"
       << ".target " << opts.sm_arch << "\n"
       << ".address_size 64\n\n";
    return ss.str();
}

} // namespace

// =========================================================================
// Fused GEMV SwiGLU PTX (Single-token decode M=1: Gate & Up + SiLU + Mul)
// =========================================================================

std::string MlFusionCompiler::emit_ptx_fused_gemv_swiglu(const target::PtxOptions& opts) {
    std::ostringstream ss;
    ss << ptx_header(opts);
    ss << R"PTX(
.visible .entry fused_gemv_swiglu_kernel(
    .param .u64 param_w_gate,
    .param .u64 param_w_up,
    .param .u64 param_x,
    .param .u64 param_y,
    .param .u32 param_n,
    .param .u32 param_k
)
{
    .reg .pred %p<16>;
    .reg .b32 %r<64>;
    .reg .b64 %rd<64>;
    .reg .f32 %f<64>;
    .shared .align 4 .f32 smem_gate[32];
    .shared .align 4 .f32 smem_up[32];

    ld.param.u64 %rd0, [param_w_gate];
    ld.param.u64 %rd1, [param_w_up];
    ld.param.u64 %rd2, [param_x];
    ld.param.u64 %rd3, [param_y];
    ld.param.u32 %r0, [param_n];
    ld.param.u32 %r1, [param_k];

    mov.u32 %r2, %ctaid.x;
    setp.ge.u32 %p0, %r2, %r0;
    @%p0 ret;

    cvt.u64.u32 %rd4, %r2;
    cvt.u64.u32 %rd5, %r1;
    mul.lo.u64 %rd6, %rd4, %rd5;
    shl.b64 %rd7, %rd6, 2;

    add.u64 %rd8, %rd0, %rd7;
    add.u64 %rd9, %rd1, %rd7;

    mov.f32 %f10, 0f00000000;
    mov.f32 %f11, 0f00000000;

    mov.u32 %r3, %tid.x;
    shl.b32 %r13, %r3, 2;
    mov.u32 %r5, %ntid.x;
    shl.b32 %r6, %r5, 2;
    mov.u32 %r12, 0;

$L_swiglu_loop:
    setp.ge.u32 %p1, %r12, %r1;
    @%p1 bra $L_swiglu_loop_end;

    add.u32 %r4, %r12, %r13;
    setp.ge.u32 %p2, %r4, %r1;
    @%p2 bra $L_swiglu_skip;

    cvt.u64.u32 %rd10, %r4;
    shl.b64 %rd11, %rd10, 2;

    add.u64 %rd12, %rd8, %rd11;
    ld.global.v4.f32 {%f20, %f21, %f22, %f23}, [%rd12];

    add.u64 %rd13, %rd9, %rd11;
    ld.global.v4.f32 {%f24, %f25, %f26, %f27}, [%rd13];

    add.u64 %rd14, %rd2, %rd11;
    ld.global.v4.f32 {%f28, %f29, %f30, %f31}, [%rd14];

    fma.rn.f32 %f10, %f20, %f28, %f10;
    fma.rn.f32 %f10, %f21, %f29, %f10;
    fma.rn.f32 %f10, %f22, %f30, %f10;
    fma.rn.f32 %f10, %f23, %f31, %f10;

    fma.rn.f32 %f11, %f24, %f28, %f11;
    fma.rn.f32 %f11, %f25, %f29, %f11;
    fma.rn.f32 %f11, %f26, %f30, %f11;
    fma.rn.f32 %f11, %f27, %f31, %f11;

$L_swiglu_skip:
    add.u32 %r12, %r12, %r6;
    bra $L_swiglu_loop;

$L_swiglu_loop_end:
    shfl.sync.down.b32 %f32, %f10, 16, 0x1f, 0xffffffff;
    add.f32 %f10, %f10, %f32;
    shfl.sync.down.b32 %f33, %f11, 16, 0x1f, 0xffffffff;
    add.f32 %f11, %f11, %f33;

    shfl.sync.down.b32 %f32, %f10, 8, 0x1f, 0xffffffff;
    add.f32 %f10, %f10, %f32;
    shfl.sync.down.b32 %f33, %f11, 8, 0x1f, 0xffffffff;
    add.f32 %f11, %f11, %f33;

    shfl.sync.down.b32 %f32, %f10, 4, 0x1f, 0xffffffff;
    add.f32 %f10, %f10, %f32;
    shfl.sync.down.b32 %f33, %f11, 4, 0x1f, 0xffffffff;
    add.f32 %f11, %f11, %f33;

    shfl.sync.down.b32 %f32, %f10, 2, 0x1f, 0xffffffff;
    add.f32 %f10, %f10, %f32;
    shfl.sync.down.b32 %f33, %f11, 2, 0x1f, 0xffffffff;
    add.f32 %f11, %f11, %f33;

    shfl.sync.down.b32 %f32, %f10, 1, 0x1f, 0xffffffff;
    add.f32 %f10, %f10, %f32;
    shfl.sync.down.b32 %f33, %f11, 1, 0x1f, 0xffffffff;
    add.f32 %f11, %f11, %f33;

    and.b32 %r7, %r3, 31;
    shr.u32 %r8, %r3, 5;
    setp.eq.u32 %p3, %r7, 0;

    mov.u32 %r20, smem_gate;
    shl.b32 %r21, %r8, 2;
    add.u32 %r22, %r20, %r21;
    @%p3 st.shared.f32 [%r22], %f10;

    mov.u32 %r23, smem_up;
    add.u32 %r24, %r23, %r21;
    @%p3 st.shared.f32 [%r24], %f11;

    bar.sync 0;

    setp.eq.u32 %p4, %r8, 0;
    @!%p4 ret;

    shr.u32 %r9, %r5, 5;
    setp.lt.u32 %p5, %r7, %r9;
    mov.f32 %f40, 0f00000000;
    mov.f32 %f41, 0f00000000;

    shl.b32 %r25, %r7, 2;
    add.u32 %r26, %r20, %r25;
    @%p5 ld.shared.f32 %f40, [%r26];
    add.u32 %r27, %r23, %r25;
    @%p5 ld.shared.f32 %f41, [%r27];

    shfl.sync.down.b32 %f42, %f40, 16, 0x1f, 0xffffffff;
    add.f32 %f40, %f40, %f42;
    shfl.sync.down.b32 %f43, %f41, 16, 0x1f, 0xffffffff;
    add.f32 %f41, %f41, %f43;

    shfl.sync.down.b32 %f42, %f40, 8, 0x1f, 0xffffffff;
    add.f32 %f40, %f40, %f42;
    shfl.sync.down.b32 %f43, %f41, 8, 0x1f, 0xffffffff;
    add.f32 %f41, %f41, %f43;

    shfl.sync.down.b32 %f42, %f40, 4, 0x1f, 0xffffffff;
    add.f32 %f40, %f40, %f42;
    shfl.sync.down.b32 %f43, %f41, 4, 0x1f, 0xffffffff;
    add.f32 %f41, %f41, %f43;

    shfl.sync.down.b32 %f42, %f40, 2, 0x1f, 0xffffffff;
    add.f32 %f40, %f40, %f42;
    shfl.sync.down.b32 %f43, %f41, 2, 0x1f, 0xffffffff;
    add.f32 %f41, %f41, %f43;

    shfl.sync.down.b32 %f42, %f40, 1, 0x1f, 0xffffffff;
    add.f32 %f40, %f40, %f42;
    shfl.sync.down.b32 %f43, %f41, 1, 0x1f, 0xffffffff;
    add.f32 %f41, %f41, %f43;

    setp.eq.u32 %p6, %r7, 0;
    @!%p6 ret;

    mov.f32 %f50, 0fBFB8AA3B;
    mul.f32 %f51, %f40, %f50;
    mov.f32 %f52, 0fC2B00000;
    max.f32 %f51, %f51, %f52;
    mov.f32 %f53, 0f42B00000;
    min.f32 %f51, %f51, %f53;

    ex2.approx.f32 %f54, %f51;
    mov.f32 %f55, 0f3F800000;
    add.f32 %f56, %f55, %f54;
    rcp.approx.f32 %f57, %f56;
    mul.f32 %f58, %f40, %f57;
    mul.f32 %f59, %f58, %f41;

    cvt.u64.u32 %rd30, %r2;
    shl.b64 %rd31, %rd30, 2;
    add.u64 %rd32, %rd3, %rd31;
    st.global.f32 [%rd32], %f59;

    ret;
}
)PTX";
    return ss.str();
}

// =========================================================================
// Fused GEMV Residual PTX (Single-token decode M=1: Down + Residual)
// =========================================================================

std::string MlFusionCompiler::emit_ptx_fused_gemv_residual(const target::PtxOptions& opts) {
    std::ostringstream ss;
    ss << ptx_header(opts);
    ss << R"PTX(
.visible .entry fused_gemv_residual_kernel(
    .param .u64 param_w_down,
    .param .u64 param_x,
    .param .u64 param_res,
    .param .u64 param_y,
    .param .u32 param_n,
    .param .u32 param_k
)
{
    .reg .pred %p<16>;
    .reg .b32 %r<64>;
    .reg .b64 %rd<64>;
    .reg .f32 %f<64>;
    .shared .align 4 .f32 smem[32];

    ld.param.u64 %rd0, [param_w_down];
    ld.param.u64 %rd1, [param_x];
    ld.param.u64 %rd2, [param_res];
    ld.param.u64 %rd3, [param_y];
    ld.param.u32 %r0, [param_n];
    ld.param.u32 %r1, [param_k];

    mov.u32 %r2, %ctaid.x;
    setp.ge.u32 %p0, %r2, %r0;
    @%p0 ret;

    cvt.u64.u32 %rd4, %r2;
    cvt.u64.u32 %rd5, %r1;
    mul.lo.u64 %rd6, %rd4, %rd5;
    shl.b64 %rd7, %rd6, 2;

    add.u64 %rd8, %rd0, %rd7;

    mov.f32 %f10, 0f00000000;

    mov.u32 %r3, %tid.x;
    shl.b32 %r13, %r3, 2;
    mov.u32 %r5, %ntid.x;
    shl.b32 %r6, %r5, 2;
    mov.u32 %r12, 0;

$L_res_loop:
    setp.ge.u32 %p1, %r12, %r1;
    @%p1 bra $L_res_loop_end;

    add.u32 %r4, %r12, %r13;
    setp.ge.u32 %p2, %r4, %r1;
    @%p2 bra $L_res_skip;

    cvt.u64.u32 %rd10, %r4;
    shl.b64 %rd11, %rd10, 2;

    add.u64 %rd12, %rd8, %rd11;
    ld.global.v4.f32 {%f20, %f21, %f22, %f23}, [%rd12];

    add.u64 %rd14, %rd1, %rd11;
    ld.global.v4.f32 {%f28, %f29, %f30, %f31}, [%rd14];

    fma.rn.f32 %f10, %f20, %f28, %f10;
    fma.rn.f32 %f10, %f21, %f29, %f10;
    fma.rn.f32 %f10, %f22, %f30, %f10;
    fma.rn.f32 %f10, %f23, %f31, %f10;

$L_res_skip:
    add.u32 %r12, %r12, %r6;
    bra $L_res_loop;

$L_res_loop_end:
    shfl.sync.down.b32 %f32, %f10, 16, 0x1f, 0xffffffff;
    add.f32 %f10, %f10, %f32;

    shfl.sync.down.b32 %f32, %f10, 8, 0x1f, 0xffffffff;
    add.f32 %f10, %f10, %f32;

    shfl.sync.down.b32 %f32, %f10, 4, 0x1f, 0xffffffff;
    add.f32 %f10, %f10, %f32;

    shfl.sync.down.b32 %f32, %f10, 2, 0x1f, 0xffffffff;
    add.f32 %f10, %f10, %f32;

    shfl.sync.down.b32 %f32, %f10, 1, 0x1f, 0xffffffff;
    add.f32 %f10, %f10, %f32;

    and.b32 %r7, %r3, 31;
    shr.u32 %r8, %r3, 5;
    setp.eq.u32 %p3, %r7, 0;

    mov.u32 %r20, smem;
    shl.b32 %r21, %r8, 2;
    add.u32 %r22, %r20, %r21;
    @%p3 st.shared.f32 [%r22], %f10;

    bar.sync 0;

    setp.eq.u32 %p4, %r8, 0;
    @!%p4 ret;

    shr.u32 %r9, %r5, 5;
    setp.lt.u32 %p5, %r7, %r9;
    mov.f32 %f40, 0f00000000;

    shl.b32 %r25, %r7, 2;
    add.u32 %r26, %r20, %r25;
    @%p5 ld.shared.f32 %f40, [%r26];

    shfl.sync.down.b32 %f42, %f40, 16, 0x1f, 0xffffffff;
    add.f32 %f40, %f40, %f42;

    shfl.sync.down.b32 %f42, %f40, 8, 0x1f, 0xffffffff;
    add.f32 %f40, %f40, %f42;

    shfl.sync.down.b32 %f42, %f40, 4, 0x1f, 0xffffffff;
    add.f32 %f40, %f40, %f42;

    shfl.sync.down.b32 %f42, %f40, 2, 0x1f, 0xffffffff;
    add.f32 %f40, %f40, %f42;

    shfl.sync.down.b32 %f42, %f40, 1, 0x1f, 0xffffffff;
    add.f32 %f40, %f40, %f42;

    setp.eq.u32 %p6, %r7, 0;
    @!%p6 ret;

    cvt.u64.u32 %rd30, %r2;
    shl.b64 %rd31, %rd30, 2;
    add.u64 %rd33, %rd2, %rd31;
    ld.global.f32 %f50, [%rd33];

    add.f32 %f51, %f40, %f50;

    add.u64 %rd32, %rd3, %rd31;
    st.global.f32 [%rd32], %f51;

    ret;
}
)PTX";
    return ss.str();
}

} // namespace brass::codegen
