// LEGACY (Stage 5a): the four hand-written PTX kernels that are now built as
// MIR in ml_fusion_ptx_kernels.cpp. The text below is byte-for-byte what
// MlFusionCompiler::emit_ptx_{swiglu,adaln_modulate,fused_residual_rms_norm}
// used to return; it exists only as the reference side of the differential
// tests in tests/unit/test_gpu_kernel_migration.cpp and is deleted in Stage 6.
// Do not extend, do not call from library code.

#include "ml_fusion_ptx_legacy.hpp"

#include <sstream>

namespace brass::codegen::legacy {

namespace {

std::string ptx_header(const target::PtxOptions& opts) {
    uint32_t major = opts.ptx_version_major;
    uint32_t minor = opts.ptx_version_minor;
    if (opts.sm_arch == "sm_89" && (major < 7 || (major == 7 && minor < 8))) {
        major = 7;
        minor = 8;
    }
    std::ostringstream ss;
    ss << "// Generated by Brass PTX Target Emitter\n"
       << ".version " << major << "." << minor << "\n"
       << ".target " << opts.sm_arch << "\n"
       << ".address_size 64\n\n";
    return ss.str();
}

} // namespace

// =========================================================================
// 1. Fused Residual RMSNorm (Parallel CUDA Block/Grid Kernel)
// =========================================================================

std::string legacy_ptx_residual_rms_norm(const target::PtxOptions& opts) {
    std::ostringstream ss;
    ss << ptx_header(opts);
    ss << R"PTX(
.visible .entry fused_residual_rms_norm_kernel(
    .param .u64 param_x,
    .param .u64 param_res,
    .param .u64 param_gamma,
    .param .u64 param_y,
    .param .u32 param_b,
    .param .u32 param_d,
    .param .f32 param_eps
)
{
    .reg .pred %p<10>;
    .reg .b32 %r<30>;
    .reg .b64 %rd<30>;
    .reg .f32 %f<60>;
    .shared .align 4 .f32 smem[32];
    .shared .align 4 .f32 s_rrms;

    ld.param.u64 %rd0, [param_x];
    ld.param.u64 %rd1, [param_res];
    ld.param.u64 %rd2, [param_gamma];
    ld.param.u64 %rd3, [param_y];
    ld.param.u32 %r0, [param_b];
    ld.param.u32 %r1, [param_d];
    ld.param.f32 %f0, [param_eps];

    mov.u32 %r2, %ctaid.x;
    setp.ge.u32 %p0, %r2, %r0;
    @%p0 ret;

    cvt.u64.u32 %rd4, %r2;
    cvt.u64.u32 %rd5, %r1;
    mul.lo.u64 %rd6, %rd4, %rd5;
    shl.b64 %rd7, %rd6, 2;

    add.u64 %rd8, %rd0, %rd7;  // x_row
    add.u64 %rd9, %rd1, %rd7;  // res_row
    add.u64 %rd10, %rd3, %rd7; // y_row

    mov.u32 %r3, %tid.x;
    mov.f32 %f1, 0f00000000;   // acc_sum_sq = 0.0f
    and.b32 %r4, %r1, 0xFFFFFFFC; // vec_d = d & ~3
    and.b32 %r27, %r1, 3;
    setp.ne.u32 %p8, %r27, 0;
    @%p8 mov.u32 %r4, 0;          // rows not 16B-aligned: scalar path

    shl.b32 %r5, %r3, 2;
    mov.u32 %r6, %ntid.x;
    shl.b32 %r7, %r6, 2;

$L_res_rms_vloop:
    setp.ge.u32 %p1, %r5, %r4;
    @%p1 bra $L_res_rms_vexit;

    cvt.u64.u32 %rd11, %r5;
    shl.b64 %rd12, %rd11, 2;
    add.u64 %rd13, %rd8, %rd12;
    add.u64 %rd14, %rd9, %rd12;

    ld.global.v4.f32 {%f2, %f3, %f4, %f5}, [%rd13];
    ld.global.v4.f32 {%f6, %f7, %f8, %f9}, [%rd14];

    add.f32 %f2, %f2, %f6;
    add.f32 %f3, %f3, %f7;
    add.f32 %f4, %f4, %f8;
    add.f32 %f5, %f5, %f9;

    st.global.v4.f32 [%rd13], {%f2, %f3, %f4, %f5};

    fma.rn.f32 %f1, %f2, %f2, %f1;
    fma.rn.f32 %f1, %f3, %f3, %f1;
    fma.rn.f32 %f1, %f4, %f4, %f1;
    fma.rn.f32 %f1, %f5, %f5, %f1;

    add.u32 %r5, %r5, %r7;
    bra $L_res_rms_vloop;

$L_res_rms_vexit:
    add.u32 %r8, %r4, %r3;
$L_res_rms_rloop:
    setp.ge.u32 %p2, %r8, %r1;
    @%p2 bra $L_res_rms_rexit;

    cvt.u64.u32 %rd15, %r8;
    shl.b64 %rd16, %rd15, 2;
    add.u64 %rd17, %rd8, %rd16;
    add.u64 %rd18, %rd9, %rd16;

    ld.global.f32 %f10, [%rd17];
    ld.global.f32 %f11, [%rd18];
    add.f32 %f10, %f10, %f11;
    st.global.f32 [%rd17], %f10;
    fma.rn.f32 %f1, %f10, %f10, %f1;

    add.u32 %r8, %r8, %r6;
    bra $L_res_rms_rloop;

$L_res_rms_rexit:
    shfl.sync.down.b32 %f12, %f1, 16, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f12;
    shfl.sync.down.b32 %f12, %f1, 8, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f12;
    shfl.sync.down.b32 %f12, %f1, 4, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f12;
    shfl.sync.down.b32 %f12, %f1, 2, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f12;
    shfl.sync.down.b32 %f12, %f1, 1, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f12;

    and.b32 %r9, %r3, 31;
    shr.u32 %r10, %r3, 5;
    setp.eq.u32 %p3, %r9, 0;

    mov.u32 %r20, smem;
    shl.b32 %r21, %r10, 2;
    add.u32 %r22, %r20, %r21;
    @%p3 st.shared.f32 [%r22], %f1;

    bar.sync 0;

    setp.eq.u32 %p4, %r10, 0;
    @!%p4 bra $L_sync_rrms;

    shr.u32 %r11, %r6, 5;
    setp.lt.u32 %p5, %r9, %r11;
    mov.f32 %f13, 0f00000000;

    shl.b32 %r23, %r9, 2;
    add.u32 %r24, %r20, %r23;
    @%p5 ld.shared.f32 %f13, [%r24];

    shfl.sync.down.b32 %f14, %f13, 16, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f14;
    shfl.sync.down.b32 %f14, %f13, 8, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f14;
    shfl.sync.down.b32 %f14, %f13, 4, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f14;
    shfl.sync.down.b32 %f14, %f13, 2, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f14;
    shfl.sync.down.b32 %f14, %f13, 1, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f14;

    @%p3 cvt.rn.f32.u32 %f15, %r1;
    @%p3 div.approx.f32 %f16, %f13, %f15;
    @%p3 add.f32 %f16, %f16, %f0;
    @%p3 rsqrt.approx.f32 %f17, %f16;
    mov.u32 %r25, s_rrms;
    @%p3 st.shared.f32 [%r25], %f17;

$L_sync_rrms:
    bar.sync 0;
    mov.u32 %r26, s_rrms;
    ld.shared.f32 %f18, [%r26];

    // Pass 2: Vector write to Y
    shl.b32 %r5, %r3, 2;
$L_p2_vec_loop:
    setp.ge.u32 %p6, %r5, %r4;
    @%p6 bra $L_p2_vec_exit;

    cvt.u64.u32 %rd11, %r5;
    shl.b64 %rd12, %rd11, 2;
    add.u64 %rd13, %rd8, %rd12;
    add.u64 %rd23, %rd2, %rd12;
    add.u64 %rd24, %rd10, %rd12;

    ld.global.v4.f32 {%f2, %f3, %f4, %f5}, [%rd13];
    ld.global.v4.f32 {%f20, %f21, %f22, %f23}, [%rd23];

    mul.f32 %f2, %f2, %f20;
    mul.f32 %f2, %f2, %f18;
    mul.f32 %f3, %f3, %f21;
    mul.f32 %f3, %f3, %f18;
    mul.f32 %f4, %f4, %f22;
    mul.f32 %f4, %f4, %f18;
    mul.f32 %f5, %f5, %f23;
    mul.f32 %f5, %f5, %f18;

    st.global.v4.f32 [%rd24], {%f2, %f3, %f4, %f5};

    add.u32 %r5, %r5, %r7;
    bra $L_p2_vec_loop;

$L_p2_vec_exit:
    add.u32 %r8, %r4, %r3;
$L_p2_rem_loop:
    setp.ge.u32 %p7, %r8, %r1;
    @%p7 bra $L_p2_rem_exit;

    cvt.u64.u32 %rd15, %r8;
    shl.b64 %rd16, %rd15, 2;
    add.u64 %rd17, %rd8, %rd16;
    add.u64 %rd25, %rd2, %rd16;
    add.u64 %rd26, %rd10, %rd16;

    ld.global.f32 %f10, [%rd17];
    ld.global.f32 %f24, [%rd25];
    mul.f32 %f10, %f10, %f24;
    mul.f32 %f10, %f10, %f18;
    st.global.f32 [%rd26], %f10;

    add.u32 %r8, %r8, %r6;
    bra $L_p2_rem_loop;

$L_p2_rem_exit:
    ret;
}

)PTX";
    return ss.str();
}

// =========================================================================
// 2. Fused SwiGLU (Elementwise Grid-Strided Vector Kernel with Fast SiLU)
// =========================================================================

std::string legacy_ptx_swiglu(const target::PtxOptions& opts) {
    std::ostringstream ss;
    ss << ptx_header(opts);
    ss << R"PTX(
.visible .entry fused_swiglu_kernel(
    .param .u64 param_gate,
    .param .u64 param_up,
    .param .u64 param_out,
    .param .u32 param_n
)
{
    .reg .pred %p<6>;
    .reg .b32 %r<30>;
    .reg .b64 %rd<30>;
    .reg .f32 %f<50>;

    ld.param.u64 %rd0, [param_gate];
    ld.param.u64 %rd1, [param_up];
    ld.param.u64 %rd2, [param_out];
    ld.param.u32 %r0, [param_n];

    mov.u32 %r3, %tid.x;
    mov.u32 %r4, %ctaid.x;
    mov.u32 %r5, %ntid.x;
    mov.u32 %r6, %nctaid.x;

    mad.lo.u32 %r7, %r4, %r5, %r3;   // vector index
    mul.lo.u32 %r8, %r6, %r5;        // vector stride
    shr.u32 %r9, %r0, 2;             // number of full 4-wide vectors

$L_swi_vloop:
    setp.ge.u32 %p0, %r7, %r9;
    @%p0 bra $L_swi_vexit;

    cvt.u64.u32 %rd3, %r7;
    shl.b64 %rd4, %rd3, 4;           // vector byte offset = idx * 16
    add.u64 %rd5, %rd0, %rd4;
    add.u64 %rd6, %rd1, %rd4;
    add.u64 %rd7, %rd2, %rd4;

    ld.global.v4.f32 {%f0, %f1, %f2, %f3}, [%rd5];
    ld.global.v4.f32 {%f4, %f5, %f6, %f7}, [%rd6];

    // elem 0: fast SiLU(f0) * f4 via ex2.approx.f32 and log2(e) 0f3FB8AA3B
    neg.f32 %f8, %f0;
    mul.f32 %f9, %f8, 0f3FB8AA3B;
    ex2.approx.f32 %f10, %f9;
    add.f32 %f11, %f10, 0f3F800000;
    rcp.approx.f32 %f12, %f11;
    mul.f32 %f13, %f0, %f12;
    mul.f32 %f14, %f13, %f4;

    // elem 1
    neg.f32 %f15, %f1;
    mul.f32 %f16, %f15, 0f3FB8AA3B;
    ex2.approx.f32 %f17, %f16;
    add.f32 %f18, %f17, 0f3F800000;
    rcp.approx.f32 %f19, %f18;
    mul.f32 %f20, %f1, %f19;
    mul.f32 %f21, %f20, %f5;

    // elem 2
    neg.f32 %f22, %f2;
    mul.f32 %f23, %f22, 0f3FB8AA3B;
    ex2.approx.f32 %f24, %f23;
    add.f32 %f25, %f24, 0f3F800000;
    rcp.approx.f32 %f26, %f25;
    mul.f32 %f27, %f2, %f26;
    mul.f32 %f28, %f27, %f6;

    // elem 3
    neg.f32 %f29, %f3;
    mul.f32 %f30, %f29, 0f3FB8AA3B;
    ex2.approx.f32 %f31, %f30;
    add.f32 %f32, %f31, 0f3F800000;
    rcp.approx.f32 %f33, %f32;
    mul.f32 %f34, %f3, %f33;
    mul.f32 %f35, %f34, %f7;

    st.global.v4.f32 [%rd7], {%f14, %f21, %f28, %f35};

    add.u32 %r7, %r7, %r8;
    bra $L_swi_vloop;

$L_swi_vexit:
    // Scalar tail: elements [n_vec, n), distributed across the grid.
    shl.b32 %r10, %r9, 2;
    add.u32 %r10, %r10, %r3;
$L_swi_rloop:
    setp.ge.u32 %p1, %r10, %r0;
    @%p1 bra $L_swi_rexit;

    cvt.u64.u32 %rd8, %r10;
    shl.b64 %rd9, %rd8, 2;
    add.u64 %rd10, %rd0, %rd9;
    add.u64 %rd11, %rd1, %rd9;
    add.u64 %rd12, %rd2, %rd9;

    ld.global.f32 %f0, [%rd10];
    ld.global.f32 %f4, [%rd11];

    neg.f32 %f8, %f0;
    mul.f32 %f9, %f8, 0f3FB8AA3B;
    ex2.approx.f32 %f10, %f9;
    add.f32 %f11, %f10, 0f3F800000;
    rcp.approx.f32 %f12, %f11;
    mul.f32 %f13, %f0, %f12;
    mul.f32 %f14, %f13, %f4;

    st.global.f32 [%rd12], %f14;

    add.u32 %r10, %r10, %r5;
    bra $L_swi_rloop;

$L_swi_rexit:
    ret;
}
)PTX";
    return ss.str();
}

// =========================================================================
// 3. Fused AdaLN Modulate (Elementwise Grid-Strided Vector Kernel)
// =========================================================================

std::string legacy_ptx_adaln_modulate(bool gated, const target::PtxOptions& opts) {
    std::ostringstream ss;
    ss << ptx_header(opts);
    if (!gated) {
        ss << R"PTX(
.visible .entry fused_adaln_modulate_kernel(
    .param .u64 param_x,
    .param .u64 param_scale,
    .param .u64 param_shift,
    .param .u64 param_y,
    .param .u32 param_l,
    .param .u32 param_d
)
{
    .reg .pred %p<6>;
    .reg .b32 %r<25>;
    .reg .b64 %rd<25>;
    .reg .f32 %f<40>;

    ld.param.u64 %rd0, [param_x];
    ld.param.u64 %rd1, [param_scale];
    ld.param.u64 %rd2, [param_shift];
    ld.param.u64 %rd3, [param_y];
    ld.param.u32 %r0, [param_l];
    ld.param.u32 %r1, [param_d];

    mov.u32 %r2, %ctaid.x;
    setp.ge.u32 %p0, %r2, %r0;
    @%p0 ret;

    cvt.u64.u32 %rd4, %r2;
    cvt.u64.u32 %rd5, %r1;
    mul.lo.u64 %rd6, %rd4, %rd5;
    shl.b64 %rd7, %rd6, 2;

    add.u64 %rd8, %rd0, %rd7; // x_row
    add.u64 %rd9, %rd3, %rd7; // y_row

    mov.u32 %r3, %tid.x;
    mov.u32 %r6, %ntid.x;
    and.b32 %r4, %r1, 0xFFFFFFFC; // vec_d = d & ~3
    and.b32 %r9, %r1, 3;
    setp.ne.u32 %p3, %r9, 0;
    @%p3 mov.u32 %r4, 0;          // rows not 16B-aligned: scalar path

    shl.b32 %r5, %r3, 2;
    shl.b32 %r7, %r6, 2;

$L_mod_vloop:
    setp.ge.u32 %p1, %r5, %r4;
    @%p1 bra $L_mod_vexit;

    cvt.u64.u32 %rd10, %r5;
    shl.b64 %rd11, %rd10, 2;
    add.u64 %rd12, %rd8, %rd11; // x
    add.u64 %rd13, %rd1, %rd11; // scale
    add.u64 %rd14, %rd2, %rd11; // shift
    add.u64 %rd15, %rd9, %rd11; // y

    ld.global.v4.f32 {%f0, %f1, %f2, %f3}, [%rd12];
    ld.global.v4.f32 {%f4, %f5, %f6, %f7}, [%rd13];
    ld.global.v4.f32 {%f8, %f9, %f10, %f11}, [%rd14];

    add.f32 %f12, %f4, 0f3F800000;
    fma.rn.f32 %f16, %f0, %f12, %f8;

    add.f32 %f13, %f5, 0f3F800000;
    fma.rn.f32 %f17, %f1, %f13, %f9;

    add.f32 %f14, %f6, 0f3F800000;
    fma.rn.f32 %f18, %f2, %f14, %f10;

    add.f32 %f15, %f7, 0f3F800000;
    fma.rn.f32 %f19, %f3, %f15, %f11;

    st.global.v4.f32 [%rd15], {%f16, %f17, %f18, %f19};

    add.u32 %r5, %r5, %r7;
    bra $L_mod_vloop;

$L_mod_vexit:
    add.u32 %r8, %r4, %r3;
$L_mod_rloop:
    setp.ge.u32 %p2, %r8, %r1;
    @%p2 bra $L_mod_rexit;

    cvt.u64.u32 %rd16, %r8;
    shl.b64 %rd17, %rd16, 2;
    add.u64 %rd18, %rd8, %rd17;
    add.u64 %rd19, %rd1, %rd17;
    add.u64 %rd20, %rd2, %rd17;
    add.u64 %rd21, %rd9, %rd17;

    ld.global.f32 %f20, [%rd18];
    ld.global.f32 %f21, [%rd19];
    ld.global.f32 %f22, [%rd20];

    add.f32 %f23, %f21, 0f3F800000;
    fma.rn.f32 %f24, %f20, %f23, %f22;

    st.global.f32 [%rd21], %f24;

    add.u32 %r8, %r8, %r6;
    bra $L_mod_rloop;

$L_mod_rexit:
    ret;
}

)PTX";
    } else {
        ss << R"PTX(
.visible .entry fused_adaln_modulate_gated_kernel(
    .param .u64 param_x,
    .param .u64 param_scale,
    .param .u64 param_shift,
    .param .u64 param_gate,
    .param .u64 param_y,
    .param .u32 param_l,
    .param .u32 param_d
)
{
    .reg .pred %p<6>;
    .reg .b32 %r<25>;
    .reg .b64 %rd<30>;
    .reg .f32 %f<40>;

    ld.param.u64 %rd0, [param_x];
    ld.param.u64 %rd1, [param_scale];
    ld.param.u64 %rd2, [param_shift];
    ld.param.u64 %rd3, [param_gate];
    ld.param.u64 %rd4, [param_y];
    ld.param.u32 %r0, [param_l];
    ld.param.u32 %r1, [param_d];

    mov.u32 %r2, %ctaid.x;
    setp.ge.u32 %p0, %r2, %r0;
    @%p0 ret;

    cvt.u64.u32 %rd5, %r2;
    cvt.u64.u32 %rd6, %r1;
    mul.lo.u64 %rd7, %rd5, %rd6;
    shl.b64 %rd8, %rd7, 2;

    add.u64 %rd9, %rd0, %rd8; // x_row
    add.u64 %rd10, %rd4, %rd8; // y_row

    mov.u32 %r3, %tid.x;
    mov.u32 %r6, %ntid.x;
    and.b32 %r4, %r1, 0xFFFFFFFC;
    and.b32 %r9, %r1, 3;
    setp.ne.u32 %p3, %r9, 0;
    @%p3 mov.u32 %r4, 0;          // rows not 16B-aligned: scalar path

    shl.b32 %r5, %r3, 2;
    shl.b32 %r7, %r6, 2;

$L_gmod_vloop:
    setp.ge.u32 %p1, %r5, %r4;
    @%p1 bra $L_gmod_vexit;

    cvt.u64.u32 %rd11, %r5;
    shl.b64 %rd12, %rd11, 2;
    add.u64 %rd13, %rd9, %rd12;  // x
    add.u64 %rd14, %rd1, %rd12;  // scale
    add.u64 %rd15, %rd2, %rd12;  // shift
    add.u64 %rd16, %rd3, %rd12;  // gate
    add.u64 %rd17, %rd10, %rd12; // y

    ld.global.v4.f32 {%f0, %f1, %f2, %f3}, [%rd13];
    ld.global.v4.f32 {%f4, %f5, %f6, %f7}, [%rd14];
    ld.global.v4.f32 {%f8, %f9, %f10, %f11}, [%rd15];
    ld.global.v4.f32 {%f12, %f13, %f14, %f15}, [%rd16];

    add.f32 %f16, %f4, 0f3F800000;
    fma.rn.f32 %f20, %f0, %f16, %f8;
    mul.f32 %f20, %f20, %f12;

    add.f32 %f17, %f5, 0f3F800000;
    fma.rn.f32 %f21, %f1, %f17, %f9;
    mul.f32 %f21, %f21, %f13;

    add.f32 %f18, %f6, 0f3F800000;
    fma.rn.f32 %f22, %f2, %f18, %f10;
    mul.f32 %f22, %f22, %f14;

    add.f32 %f19, %f7, 0f3F800000;
    fma.rn.f32 %f23, %f3, %f19, %f11;
    mul.f32 %f23, %f23, %f15;

    st.global.v4.f32 [%rd17], {%f20, %f21, %f22, %f23};

    add.u32 %r5, %r5, %r7;
    bra $L_gmod_vloop;

$L_gmod_vexit:
    add.u32 %r8, %r4, %r3;
$L_gmod_rloop:
    setp.ge.u32 %p2, %r8, %r1;
    @%p2 bra $L_gmod_rexit;

    cvt.u64.u32 %rd18, %r8;
    shl.b64 %rd19, %rd18, 2;
    add.u64 %rd20, %rd9, %rd19;
    add.u64 %rd21, %rd1, %rd19;
    add.u64 %rd22, %rd2, %rd19;
    add.u64 %rd23, %rd3, %rd19;
    add.u64 %rd24, %rd10, %rd19;

    ld.global.f32 %f24, [%rd20];
    ld.global.f32 %f25, [%rd21];
    ld.global.f32 %f26, [%rd22];
    ld.global.f32 %f27, [%rd23];

    add.f32 %f28, %f25, 0f3F800000;
    fma.rn.f32 %f29, %f24, %f28, %f26;
    mul.f32 %f29, %f29, %f27;

    st.global.f32 [%rd24], %f29;

    add.u32 %r8, %r8, %r6;
    bra $L_gmod_rloop;

$L_gmod_rexit:
    ret;
}

)PTX";
    }
    return ss.str();
}

} // namespace brass::codegen::legacy
