#include <brass/codegen/ml_fusion.hpp>
#include <sstream>

namespace brass::codegen {

namespace {

std::string ptx_header(const target::PtxOptions& opts) {
    uint32_t major = opts.ptx_version_major;
    uint32_t minor = opts.ptx_version_minor;
    if (opts.sm_arch == "sm_89" && (major < 7 || (major == 7 && minor < 8))) {
        major = 7;
        minor = 8;
    }
    std::ostringstream ss;
    ss << "// Generated by Brass PTX Target Emitter\n"
       << ".version " << major << "." << minor << "\n"
       << ".target " << opts.sm_arch << "\n"
       << ".address_size 64\n\n";
    return ss.str();
}

} // namespace

// =========================================================================
// 1. Fused Residual RMSNorm, SwiGLU, AdaLN modulate: MIR kernels
//    (ml_fusion_ptx_kernels.cpp) lowered through PtxISel. The former string
//    templates live in ml_fusion_ptx_legacy.cpp until Stage 6.
// =========================================================================

std::string MlFusionCompiler::emit_ptx_fused_residual_rms_norm(const target::PtxOptions& opts) {
    Module mod("mod_ptx_residual_rms_norm");
    Function* fn = build_ptx_residual_rms_norm(mod);
    return target::PtxTarget::emit_function(*fn, opts);
}

std::string MlFusionCompiler::emit_ptx_residual_rms_norm(const target::PtxOptions& opts) {
    return emit_ptx_fused_residual_rms_norm(opts);
}

std::string MlFusionCompiler::emit_ptx_swiglu(const target::PtxOptions& opts) {
    Module mod("mod_ptx_swiglu");
    Function* fn = build_ptx_swiglu(mod);
    return target::PtxTarget::emit_function(*fn, opts);
}

std::string MlFusionCompiler::emit_ptx_adaln_modulate(bool gated, const target::PtxOptions& opts) {
    Module mod(gated ? "mod_ptx_adaln_gated" : "mod_ptx_adaln");
    Function* fn = build_ptx_adaln_modulate(mod, gated);
    return target::PtxTarget::emit_function(*fn, opts);
}

// =========================================================================
// 2. Fused LayerNorm + Modulate (Parallel CUDA Block/Grid Kernel)
// =========================================================================

std::string MlFusionCompiler::emit_ptx_fused_layernorm_modulate(const target::PtxOptions& opts) {
    std::ostringstream ss;
    ss << ptx_header(opts);
    ss << R"PTX(
.visible .entry fused_layernorm_modulate_kernel(
    .param .u64 param_x,
    .param .u64 param_gamma,
    .param .u64 param_beta,
    .param .u64 param_scale,
    .param .u64 param_shift,
    .param .u64 param_y,
    .param .u32 param_r,
    .param .u32 param_d,
    .param .f32 param_eps
)
{
    .reg .pred %p<12>;
    .reg .b32 %r<35>;
    .reg .b64 %rd<35>;
    .reg .f32 %f<70>;
    .shared .align 4 .f32 smem[32];
    .shared .align 4 .f32 s_mean;
    .shared .align 4 .f32 s_rstd;

    ld.param.u64 %rd0, [param_x];
    ld.param.u64 %rd1, [param_gamma];
    ld.param.u64 %rd2, [param_beta];
    ld.param.u64 %rd3, [param_scale];
    ld.param.u64 %rd4, [param_shift];
    ld.param.u64 %rd5, [param_y];
    ld.param.u32 %r0, [param_r];
    ld.param.u32 %r1, [param_d];
    ld.param.f32 %f0, [param_eps];

    mov.u32 %r2, %ctaid.x;
    setp.ge.u32 %p0, %r2, %r0;
    @%p0 ret;

    cvt.u64.u32 %rd6, %r2;
    cvt.u64.u32 %rd7, %r1;
    mul.lo.u64 %rd8, %rd6, %rd7;
    shl.b64 %rd9, %rd8, 2;

    add.u64 %rd10, %rd0, %rd9; // x_row
    add.u64 %rd11, %rd5, %rd9; // y_row

    mov.u32 %r3, %tid.x;
    mov.u32 %r6, %ntid.x;
    and.b32 %r4, %r1, 0xFFFFFFFC; // vec_d = d & ~3
    and.b32 %r29, %r1, 3;
    setp.ne.u32 %p10, %r29, 0;
    @%p10 mov.u32 %r4, 0;          // rows not 16B-aligned: scalar path

    // ================= Pass 1: Mean =================
    mov.f32 %f1, 0f00000000;
    shl.b32 %r5, %r3, 2;
    shl.b32 %r7, %r6, 2;

$L_ln_p1_vloop:
    setp.ge.u32 %p1, %r5, %r4;
    @%p1 bra $L_ln_p1_vexit;

    cvt.u64.u32 %rd12, %r5;
    shl.b64 %rd13, %rd12, 2;
    add.u64 %rd14, %rd10, %rd13;

    ld.global.v4.f32 {%f2, %f3, %f4, %f5}, [%rd14];
    add.f32 %f1, %f1, %f2;
    add.f32 %f1, %f1, %f3;
    add.f32 %f1, %f1, %f4;
    add.f32 %f1, %f1, %f5;

    add.u32 %r5, %r5, %r7;
    bra $L_ln_p1_vloop;

$L_ln_p1_vexit:
    add.u32 %r8, %r4, %r3;
$L_ln_p1_rloop:
    setp.ge.u32 %p2, %r8, %r1;
    @%p2 bra $L_ln_p1_rexit;

    cvt.u64.u32 %rd15, %r8;
    shl.b64 %rd16, %rd15, 2;
    add.u64 %rd17, %rd10, %rd16;
    ld.global.f32 %f6, [%rd17];
    add.f32 %f1, %f1, %f6;

    add.u32 %r8, %r8, %r6;
    bra $L_ln_p1_rloop;

$L_ln_p1_rexit:
    shfl.sync.down.b32 %f7, %f1, 16, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f7;
    shfl.sync.down.b32 %f7, %f1, 8, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f7;
    shfl.sync.down.b32 %f7, %f1, 4, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f7;
    shfl.sync.down.b32 %f7, %f1, 2, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f7;
    shfl.sync.down.b32 %f7, %f1, 1, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f7;

    and.b32 %r9, %r3, 31;
    shr.u32 %r10, %r3, 5;
    setp.eq.u32 %p3, %r9, 0;

    mov.u32 %r20, smem;
    shl.b32 %r21, %r10, 2;
    add.u32 %r22, %r20, %r21;
    @%p3 st.shared.f32 [%r22], %f1;

    bar.sync 0;

    setp.eq.u32 %p4, %r10, 0;
    @!%p4 bra $L_ln_sync_mean;

    shr.u32 %r11, %r6, 5;
    setp.lt.u32 %p5, %r9, %r11;
    mov.f32 %f8, 0f00000000;

    shl.b32 %r23, %r9, 2;
    add.u32 %r24, %r20, %r23;
    @%p5 ld.shared.f32 %f8, [%r24];

    shfl.sync.down.b32 %f9, %f8, 16, 0x1f, 0xffffffff;
    add.f32 %f8, %f8, %f9;
    shfl.sync.down.b32 %f9, %f8, 8, 0x1f, 0xffffffff;
    add.f32 %f8, %f8, %f9;
    shfl.sync.down.b32 %f9, %f8, 4, 0x1f, 0xffffffff;
    add.f32 %f8, %f8, %f9;
    shfl.sync.down.b32 %f9, %f8, 2, 0x1f, 0xffffffff;
    add.f32 %f8, %f8, %f9;
    shfl.sync.down.b32 %f9, %f8, 1, 0x1f, 0xffffffff;
    add.f32 %f8, %f8, %f9;

    @%p3 cvt.rn.f32.u32 %f10, %r1;
    @%p3 div.approx.f32 %f11, %f8, %f10;
    mov.u32 %r25, s_mean;
    @%p3 st.shared.f32 [%r25], %f11;

$L_ln_sync_mean:
    bar.sync 0;
    mov.u32 %r26, s_mean;
    ld.shared.f32 %f12, [%r26];

    // ================= Pass 2: Variance =================
    mov.f32 %f13, 0f00000000;
    shl.b32 %r5, %r3, 2;

$L_ln_p2_vloop:
    setp.ge.u32 %p6, %r5, %r4;
    @%p6 bra $L_ln_p2_vexit;

    cvt.u64.u32 %rd12, %r5;
    shl.b64 %rd13, %rd12, 2;
    add.u64 %rd14, %rd10, %rd13;

    ld.global.v4.f32 {%f14, %f15, %f16, %f17}, [%rd14];
    sub.f32 %f14, %f14, %f12;
    sub.f32 %f15, %f15, %f12;
    sub.f32 %f16, %f16, %f12;
    sub.f32 %f17, %f17, %f12;

    fma.rn.f32 %f13, %f14, %f14, %f13;
    fma.rn.f32 %f13, %f15, %f15, %f13;
    fma.rn.f32 %f13, %f16, %f16, %f13;
    fma.rn.f32 %f13, %f17, %f17, %f13;

    add.u32 %r5, %r5, %r7;
    bra $L_ln_p2_vloop;

$L_ln_p2_vexit:
    add.u32 %r8, %r4, %r3;
$L_ln_p2_rloop:
    setp.ge.u32 %p7, %r8, %r1;
    @%p7 bra $L_ln_p2_rexit;

    cvt.u64.u32 %rd15, %r8;
    shl.b64 %rd16, %rd15, 2;
    add.u64 %rd17, %rd10, %rd16;
    ld.global.f32 %f18, [%rd17];
    sub.f32 %f18, %f18, %f12;
    fma.rn.f32 %f13, %f18, %f18, %f13;

    add.u32 %r8, %r8, %r6;
    bra $L_ln_p2_rloop;

$L_ln_p2_rexit:
    shfl.sync.down.b32 %f19, %f13, 16, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f19;
    shfl.sync.down.b32 %f19, %f13, 8, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f19;
    shfl.sync.down.b32 %f19, %f13, 4, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f19;
    shfl.sync.down.b32 %f19, %f13, 2, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f19;
    shfl.sync.down.b32 %f19, %f13, 1, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f19;

    @%p3 st.shared.f32 [%r22], %f13;

    bar.sync 0;

    @!%p4 bra $L_ln_sync_rstd;

    mov.f32 %f20, 0f00000000;
    @%p5 ld.shared.f32 %f20, [%r24];

    shfl.sync.down.b32 %f21, %f20, 16, 0x1f, 0xffffffff;
    add.f32 %f20, %f20, %f21;
    shfl.sync.down.b32 %f21, %f20, 8, 0x1f, 0xffffffff;
    add.f32 %f20, %f20, %f21;
    shfl.sync.down.b32 %f21, %f20, 4, 0x1f, 0xffffffff;
    add.f32 %f20, %f20, %f21;
    shfl.sync.down.b32 %f21, %f20, 2, 0x1f, 0xffffffff;
    add.f32 %f20, %f20, %f21;
    shfl.sync.down.b32 %f21, %f20, 1, 0x1f, 0xffffffff;
    add.f32 %f20, %f20, %f21;

    @%p3 cvt.rn.f32.u32 %f22, %r1;
    @%p3 div.approx.f32 %f23, %f20, %f22;
    @%p3 add.f32 %f23, %f23, %f0;
    @%p3 rsqrt.approx.f32 %f24, %f23;
    mov.u32 %r27, s_rstd;
    @%p3 st.shared.f32 [%r27], %f24;

$L_ln_sync_rstd:
    bar.sync 0;
    mov.u32 %r28, s_rstd;
    ld.shared.f32 %f25, [%r28];

    // ================= Pass 3: In-register LN + Modulate =================
    shl.b32 %r5, %r3, 2;

$L_ln_p3_vloop:
    setp.ge.u32 %p8, %r5, %r4;
    @%p8 bra $L_ln_p3_vexit;

    cvt.u64.u32 %rd12, %r5;
    shl.b64 %rd13, %rd12, 2;
    add.u64 %rd14, %rd10, %rd13; // x
    add.u64 %rd18, %rd1, %rd13;  // gamma
    add.u64 %rd19, %rd2, %rd13;  // beta
    add.u64 %rd20, %rd3, %rd13;  // scale
    add.u64 %rd21, %rd4, %rd13;  // shift
    add.u64 %rd22, %rd11, %rd13; // y

    ld.global.v4.f32 {%f26, %f27, %f28, %f29}, [%rd14];
    ld.global.v4.f32 {%f30, %f31, %f32, %f33}, [%rd18];
    ld.global.v4.f32 {%f34, %f35, %f36, %f37}, [%rd19];
    ld.global.v4.f32 {%f38, %f39, %f40, %f41}, [%rd20];
    ld.global.v4.f32 {%f42, %f43, %f44, %f45}, [%rd21];

    // elem 0
    sub.f32 %f46, %f26, %f12;
    mul.f32 %f46, %f46, %f25;
    fma.rn.f32 %f46, %f46, %f30, %f34;
    add.f32 %f47, %f38, 0f3F800000;
    fma.rn.f32 %f46, %f46, %f47, %f42;

    // elem 1
    sub.f32 %f48, %f27, %f12;
    mul.f32 %f48, %f48, %f25;
    fma.rn.f32 %f48, %f48, %f31, %f35;
    add.f32 %f49, %f39, 0f3F800000;
    fma.rn.f32 %f48, %f48, %f49, %f43;

    // elem 2
    sub.f32 %f50, %f28, %f12;
    mul.f32 %f50, %f50, %f25;
    fma.rn.f32 %f50, %f50, %f32, %f36;
    add.f32 %f51, %f40, 0f3F800000;
    fma.rn.f32 %f50, %f50, %f51, %f44;

    // elem 3
    sub.f32 %f52, %f29, %f12;
    mul.f32 %f52, %f52, %f25;
    fma.rn.f32 %f52, %f52, %f33, %f37;
    add.f32 %f53, %f41, 0f3F800000;
    fma.rn.f32 %f52, %f52, %f53, %f45;

    st.global.v4.f32 [%rd22], {%f46, %f48, %f50, %f52};

    add.u32 %r5, %r5, %r7;
    bra $L_ln_p3_vloop;

$L_ln_p3_vexit:
    add.u32 %r8, %r4, %r3;
$L_ln_p3_rloop:
    setp.ge.u32 %p9, %r8, %r1;
    @%p9 bra $L_ln_p3_rexit;

    cvt.u64.u32 %rd15, %r8;
    shl.b64 %rd16, %rd15, 2;
    add.u64 %rd17, %rd10, %rd16;
    add.u64 %rd23, %rd1, %rd16;
    add.u64 %rd24, %rd2, %rd16;
    add.u64 %rd25, %rd3, %rd16;
    add.u64 %rd26, %rd4, %rd16;
    add.u64 %rd27, %rd11, %rd16;

    ld.global.f32 %f54, [%rd17];
    ld.global.f32 %f55, [%rd23];
    ld.global.f32 %f56, [%rd24];
    ld.global.f32 %f57, [%rd25];
    ld.global.f32 %f58, [%rd26];

    sub.f32 %f59, %f54, %f12;
    mul.f32 %f59, %f59, %f25;
    fma.rn.f32 %f59, %f59, %f55, %f56;
    add.f32 %f60, %f57, 0f3F800000;
    fma.rn.f32 %f59, %f59, %f60, %f58;

    st.global.f32 [%rd27], %f59;

    add.u32 %r8, %r8, %r6;
    bra $L_ln_p3_rloop;

$L_ln_p3_rexit:
    ret;
}
)PTX";
    return ss.str();
}

} // namespace brass::codegen
