#include <brass/codegen/ml_fusion.hpp>
#include <sstream>

namespace brass::codegen {

namespace {

std::string ptx_header(const target::PtxOptions& opts) {
    uint32_t major = opts.ptx_version_major;
    uint32_t minor = opts.ptx_version_minor;
    if (opts.sm_arch == "sm_89" && (major < 7 || (major == 7 && minor < 8))) {
        major = 7;
        minor = 8;
    }
    std::ostringstream ss;
    ss << "// Generated by Brass PTX Target Emitter\n"
       << ".version " << major << "." << minor << "\n"
       << ".target " << opts.sm_arch << "\n"
       << ".address_size 64\n\n";
    return ss.str();
}

} // namespace

// =========================================================================
// Fused Residual LayerNorm (Parallel CUDA Block/Grid Kernel)
// =========================================================================
// Pass 1: X[i] += res[i] in-place, accumulates cooperative mean across D.
// Pass 2: Cooperatively computes variance across D.
// Pass 3: Computes Y[i] = ((X[i] - mean) * rstd) * gamma[i] + beta[i].

std::string MlFusionCompiler::emit_ptx_fused_residual_layernorm(const target::PtxOptions& opts) {
    std::ostringstream ss;
    ss << ptx_header(opts);
    ss << R"PTX(
.visible .entry fused_residual_layernorm_kernel(
    .param .u64 param_x,
    .param .u64 param_res,
    .param .u64 param_gamma,
    .param .u64 param_beta,
    .param .u64 param_y,
    .param .u32 param_b,
    .param .u32 param_d,
    .param .f32 param_eps
)
{
    .reg .pred %p<15>;
    .reg .b32 %r<40>;
    .reg .b64 %rd<40>;
    .reg .f32 %f<70>;
    .shared .align 4 .f32 smem[32];
    .shared .align 4 .f32 s_mean;
    .shared .align 4 .f32 s_rstd;

    ld.param.u64 %rd0, [param_x];
    ld.param.u64 %rd1, [param_res];
    ld.param.u64 %rd2, [param_gamma];
    ld.param.u64 %rd3, [param_beta];
    ld.param.u64 %rd4, [param_y];
    ld.param.u32 %r0, [param_b];
    ld.param.u32 %r1, [param_d];
    ld.param.f32 %f0, [param_eps];

    mov.u32 %r2, %ctaid.x;
    setp.ge.u32 %p0, %r2, %r0;
    @%p0 ret;

    cvt.u64.u32 %rd5, %r2;
    cvt.u64.u32 %rd6, %r1;
    mul.lo.u64 %rd7, %rd5, %rd6;
    shl.b64 %rd8, %rd7, 2;

    add.u64 %rd9, %rd0, %rd8;  // x_row
    add.u64 %rd10, %rd1, %rd8; // res_row
    add.u64 %rd11, %rd4, %rd8; // y_row

    mov.u32 %r3, %tid.x;
    mov.u32 %r6, %ntid.x;
    and.b32 %r4, %r1, 0xFFFFFFFC; // vec_d = d & ~3

    // ================= Pass 1: Mean (with in-place X += res) =================
    mov.f32 %f1, 0f00000000;
    shl.b32 %r5, %r3, 2;
    shl.b32 %r7, %r6, 2;

$L_res_ln_p1_vloop:
    setp.ge.u32 %p1, %r5, %r4;
    @%p1 bra $L_res_ln_p1_vexit;

    cvt.u64.u32 %rd12, %r5;
    shl.b64 %rd13, %rd12, 2;
    add.u64 %rd14, %rd9, %rd13;
    add.u64 %rd15, %rd10, %rd13;

    ld.global.v4.f32 {%f2, %f3, %f4, %f5}, [%rd14];
    ld.global.v4.f32 {%f6, %f7, %f8, %f9}, [%rd15];

    add.f32 %f2, %f2, %f6;
    add.f32 %f3, %f3, %f7;
    add.f32 %f4, %f4, %f8;
    add.f32 %f5, %f5, %f9;

    st.global.v4.f32 [%rd14], {%f2, %f3, %f4, %f5};

    add.f32 %f1, %f1, %f2;
    add.f32 %f1, %f1, %f3;
    add.f32 %f1, %f1, %f4;
    add.f32 %f1, %f1, %f5;

    add.u32 %r5, %r5, %r7;
    bra $L_res_ln_p1_vloop;

$L_res_ln_p1_vexit:
    add.u32 %r8, %r4, %r3;
$L_res_ln_p1_rloop:
    setp.ge.u32 %p2, %r8, %r1;
    @%p2 bra $L_res_ln_p1_rexit;

    cvt.u64.u32 %rd16, %r8;
    shl.b64 %rd17, %rd16, 2;
    add.u64 %rd18, %rd9, %rd17;
    add.u64 %rd19, %rd10, %rd17;

    ld.global.f32 %f6, [%rd18];
    ld.global.f32 %f7, [%rd19];
    add.f32 %f6, %f6, %f7;
    st.global.f32 [%rd18], %f6;
    add.f32 %f1, %f1, %f6;

    add.u32 %r8, %r8, %r6;
    bra $L_res_ln_p1_rloop;

$L_res_ln_p1_rexit:
    shfl.sync.down.b32 %f7, %f1, 16, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f7;
    shfl.sync.down.b32 %f7, %f1, 8, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f7;
    shfl.sync.down.b32 %f7, %f1, 4, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f7;
    shfl.sync.down.b32 %f7, %f1, 2, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f7;
    shfl.sync.down.b32 %f7, %f1, 1, 0x1f, 0xffffffff;
    add.f32 %f1, %f1, %f7;

    and.b32 %r9, %r3, 31;
    shr.u32 %r10, %r3, 5;
    setp.eq.u32 %p3, %r9, 0;

    mov.u32 %r20, smem;
    shl.b32 %r21, %r10, 2;
    add.u32 %r22, %r20, %r21;
    @%p3 st.shared.f32 [%r22], %f1;

    bar.sync 0;

    setp.eq.u32 %p4, %r10, 0;
    @!%p4 bra $L_res_ln_sync_mean;

    shr.u32 %r11, %r6, 5;
    setp.lt.u32 %p5, %r9, %r11;
    mov.f32 %f8, 0f00000000;

    shl.b32 %r23, %r9, 2;
    add.u32 %r24, %r20, %r23;
    @%p5 ld.shared.f32 %f8, [%r24];

    shfl.sync.down.b32 %f9, %f8, 16, 0x1f, 0xffffffff;
    add.f32 %f8, %f8, %f9;
    shfl.sync.down.b32 %f9, %f8, 8, 0x1f, 0xffffffff;
    add.f32 %f8, %f8, %f9;
    shfl.sync.down.b32 %f9, %f8, 4, 0x1f, 0xffffffff;
    add.f32 %f8, %f8, %f9;
    shfl.sync.down.b32 %f9, %f8, 2, 0x1f, 0xffffffff;
    add.f32 %f8, %f8, %f9;
    shfl.sync.down.b32 %f9, %f8, 1, 0x1f, 0xffffffff;
    add.f32 %f8, %f8, %f9;

    @%p3 cvt.rn.f32.u32 %f10, %r1;
    @%p3 div.approx.f32 %f11, %f8, %f10;
    mov.u32 %r25, s_mean;
    @%p3 st.shared.f32 [%r25], %f11;

$L_res_ln_sync_mean:
    bar.sync 0;
    mov.u32 %r26, s_mean;
    ld.shared.f32 %f12, [%r26];

    // ================= Pass 2: Variance =================
    mov.f32 %f13, 0f00000000;
    shl.b32 %r5, %r3, 2;

$L_res_ln_p2_vloop:
    setp.ge.u32 %p6, %r5, %r4;
    @%p6 bra $L_res_ln_p2_vexit;

    cvt.u64.u32 %rd12, %r5;
    shl.b64 %rd13, %rd12, 2;
    add.u64 %rd14, %rd9, %rd13;

    ld.global.v4.f32 {%f14, %f15, %f16, %f17}, [%rd14];
    sub.f32 %f14, %f14, %f12;
    sub.f32 %f15, %f15, %f12;
    sub.f32 %f16, %f16, %f12;
    sub.f32 %f17, %f17, %f12;

    fma.rn.f32 %f13, %f14, %f14, %f13;
    fma.rn.f32 %f13, %f15, %f15, %f13;
    fma.rn.f32 %f13, %f16, %f16, %f13;
    fma.rn.f32 %f13, %f17, %f17, %f13;

    add.u32 %r5, %r5, %r7;
    bra $L_res_ln_p2_vloop;

$L_res_ln_p2_vexit:
    add.u32 %r8, %r4, %r3;
$L_res_ln_p2_rloop:
    setp.ge.u32 %p7, %r8, %r1;
    @%p7 bra $L_res_ln_p2_rexit;

    cvt.u64.u32 %rd16, %r8;
    shl.b64 %rd17, %rd16, 2;
    add.u64 %rd18, %rd9, %rd17;
    ld.global.f32 %f18, [%rd18];
    sub.f32 %f18, %f18, %f12;
    fma.rn.f32 %f13, %f18, %f18, %f13;

    add.u32 %r8, %r8, %r6;
    bra $L_res_ln_p2_rloop;

$L_res_ln_p2_rexit:
    shfl.sync.down.b32 %f19, %f13, 16, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f19;
    shfl.sync.down.b32 %f19, %f13, 8, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f19;
    shfl.sync.down.b32 %f19, %f13, 4, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f19;
    shfl.sync.down.b32 %f19, %f13, 2, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f19;
    shfl.sync.down.b32 %f19, %f13, 1, 0x1f, 0xffffffff;
    add.f32 %f13, %f13, %f19;

    @%p3 st.shared.f32 [%r22], %f13;

    bar.sync 0;

    @!%p4 bra $L_res_ln_sync_rstd;

    mov.f32 %f20, 0f00000000;
    @%p5 ld.shared.f32 %f20, [%r24];

    shfl.sync.down.b32 %f21, %f20, 16, 0x1f, 0xffffffff;
    add.f32 %f20, %f20, %f21;
    shfl.sync.down.b32 %f21, %f20, 8, 0x1f, 0xffffffff;
    add.f32 %f20, %f20, %f21;
    shfl.sync.down.b32 %f21, %f20, 4, 0x1f, 0xffffffff;
    add.f32 %f20, %f20, %f21;
    shfl.sync.down.b32 %f21, %f20, 2, 0x1f, 0xffffffff;
    add.f32 %f20, %f20, %f21;
    shfl.sync.down.b32 %f21, %f20, 1, 0x1f, 0xffffffff;
    add.f32 %f20, %f20, %f21;

    @%p3 cvt.rn.f32.u32 %f22, %r1;
    @%p3 div.approx.f32 %f23, %f20, %f22;
    @%p3 add.f32 %f23, %f23, %f0;
    @%p3 rsqrt.approx.f32 %f24, %f23;
    mov.u32 %r27, s_rstd;
    @%p3 st.shared.f32 [%r27], %f24;

$L_res_ln_sync_rstd:
    bar.sync 0;
    mov.u32 %r28, s_rstd;
    ld.shared.f32 %f25, [%r28];

    // ================= Pass 3: In-register Normalized Y =================
    shl.b32 %r5, %r3, 2;

$L_res_ln_p3_vloop:
    setp.ge.u32 %p8, %r5, %r4;
    @%p8 bra $L_res_ln_p3_vexit;

    cvt.u64.u32 %rd12, %r5;
    shl.b64 %rd13, %rd12, 2;
    add.u64 %rd14, %rd9, %rd13;  // x
    add.u64 %rd18, %rd2, %rd13;  // gamma
    add.u64 %rd19, %rd3, %rd13;  // beta
    add.u64 %rd22, %rd11, %rd13; // y

    ld.global.v4.f32 {%f26, %f27, %f28, %f29}, [%rd14];
    ld.global.v4.f32 {%f30, %f31, %f32, %f33}, [%rd18];
    ld.global.v4.f32 {%f34, %f35, %f36, %f37}, [%rd19];

    // elem 0
    sub.f32 %f40, %f26, %f12;
    mul.f32 %f40, %f40, %f25;
    fma.rn.f32 %f40, %f40, %f30, %f34;

    // elem 1
    sub.f32 %f41, %f27, %f12;
    mul.f32 %f41, %f41, %f25;
    fma.rn.f32 %f41, %f41, %f31, %f35;

    // elem 2
    sub.f32 %f42, %f28, %f12;
    mul.f32 %f42, %f42, %f25;
    fma.rn.f32 %f42, %f42, %f32, %f36;

    // elem 3
    sub.f32 %f43, %f29, %f12;
    mul.f32 %f43, %f43, %f25;
    fma.rn.f32 %f43, %f43, %f33, %f37;

    st.global.v4.f32 [%rd22], {%f40, %f41, %f42, %f43};

    add.u32 %r5, %r5, %r7;
    bra $L_res_ln_p3_vloop;

$L_res_ln_p3_vexit:
    add.u32 %r8, %r4, %r3;
$L_res_ln_p3_rloop:
    setp.ge.u32 %p9, %r8, %r1;
    @%p9 bra $L_res_ln_p3_rexit;

    cvt.u64.u32 %rd16, %r8;
    shl.b64 %rd17, %rd16, 2;
    add.u64 %rd18, %rd9, %rd17;  // x
    add.u64 %rd23, %rd2, %rd17;  // gamma
    add.u64 %rd24, %rd3, %rd17;  // beta
    add.u64 %rd25, %rd11, %rd17; // y

    ld.global.f32 %f44, [%rd18];
    ld.global.f32 %f45, [%rd23];
    ld.global.f32 %f46, [%rd24];

    sub.f32 %f44, %f44, %f12;
    mul.f32 %f44, %f44, %f25;
    fma.rn.f32 %f44, %f44, %f45, %f46;
    st.global.f32 [%rd25], %f44;

    add.u32 %r8, %r8, %r6;
    bra $L_res_ln_p3_rloop;

$L_res_ln_p3_rexit:
    ret;
}

.visible .entry fused_residual_layernorm(.param .u64 p0) { ret; }
)PTX";
    return ss.str();
}

} // namespace brass::codegen
